#pragma once
#define _USE_MATH_DEFINES
#include <math.h>
#include <iostream>
#include "../Config.h"
#include <vector>

/* Defines all the parameters set pre-compiling
<->
---> MHD: Is the gas MHD (B != 0) ?
---> CYLINDRICAL: Are we using cylindrical coordinates ?
---> HLL/HLLC/HLLD: What Riemann are we using ? (HLLD default for MHD, HLLC default for HD)
---> TRACING: Do we perform characteristic tracing in the reconstruction ?
---> NGHOST: The number of ghost cells added to N in each direction
---> NVAL: The numbe of variables in u (MHD? Iso?)
---> NWAVES: The number of characteristic waves (and the number of eigenvectors/eigenvalues)
<->
*/

/* In the Config.h header (generated by bash script): 
#define MHD
#define CYLINDRICAL
#define ISO
#define HLLD				 Use the HLLD Riemann Solver ? 
#define HLLC				 Use the HLLC Riemann Solver ? 
#define HLLE				 Use the HLLE Riemann Solver ? 
#define TRACING				 Do the characteristic tracing ?
#define CHAR                 Monotonicity constraints in characteristic variables ?
*/

#define PRIMBOUNDS

#ifdef MHD
  #define NGHOST 3
#else
  #define NGHOST 2
#endif // MHD

#define NGHOST 3

#ifdef MHD
  #define NVAL 8
  #ifdef ISO
    #define NWAVE 6
  #else
    #define NWAVE 7
  #endif // ISO
#else
  #define NVAL 5
  #ifdef ISO
    #define NWAVE 4
  #else
    #define NWAVE 5
  #endif // ISO
#endif // MHD

#define WV (NWAVE-1)/2

//#define CT

enum class bounds
{
    PERIODIC,
    OUTFLOW,
    REFLECTING,
    PRESSURE    /* For RT instability, extrapolate pressure with grav. potential to ghost cells to improve conservation of energy */
};

enum class exports
{
    PRIM,
    CONS,
    Rho,
    Vvec,
    VX,
    VY,
    VZ,
    Mvec,
    MX,
    MY,
    MZ,
    E,
    P,
    Bvec,
    Bx,
    By,
    Bz,
    DIVB
};

std::string exp_names[18] = {
    "Primitive_variables",
    "Conserved_variable",
    "Density",
    "Velocity_vector",
    "Vx",
    "Vy",
    "Vz",
    "Momentum_vector",
    "Mx",
    "My",
    "Mz",
    "Energy",
    "Pressure",
    "MagnField_vector",
    "Bx",
    "By",
    "Bz",
    "B_Divergence"
};

struct Export
{
    int type = 0; /*0: vtk    1: csv */
    std::vector<exports> exp;   /* What variables to export ?*/

    int xType;  /* 0: export the whole dimension    1: average across the whole dimension    2: take slice at n-th cell*/
    int xSlice = 0; /* Slice at xSlice-th cell */
    int yType;
    int ySlice = 0;
    int zType;
    int zSlice = 0;

    bool ghosts = false;

    std::string name = "output";
    
};